# Generated by Django 2.1.2 on 2018-12-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200)),
                ('costo_presupuestado', models.IntegerField(default=0)),
                ('costo_real', models.IntegerField(default=0)),
                ('id_tienda', models.CharField(max_length=200)),
                ('comentarios', models.CharField(max_length=200)),
                ('unidad', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
