# Generated by Django 2.1.2 on 2018-12-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='aprobado',
            field=models.BooleanField(default=True),
        ),
    ]
